- name: Reset K8S Cluster
  hosts: k8s
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')

    - name: Reset kubeadm
      command: "kubeadm reset --force"

    - name: Remove installed files
      apt:
        name: "{{ packages }}"
        state: absent
        purge: yes
      vars:
        packages:
        - docker
        - docker-ce
        - docker-ce-cli 
        - containerd.io
        - kubeadm
        - kubectl
        - kubelet
    
    - name: Remove users kubeconfig
      ansible.builtin.file:
        path: /home/{{ansible_user}}/.kube
        state: absent


