- hosts: k8sworker
  tasks:     
  # Initialize the cluster using kubeadm
  - name: Copy the join command to server location
    copy: src="./join_command.txt" dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh